const cors = require('cors')
const express = require('express')
const mongoose = require('mongoose')
const router = express.Router()
const app = express()
const productRoute = require('./end-points/products/productRoute')
app.use(cors())
app.use(express.json())
app.use('products',productRoute)
module.exports = app