const mongoose = require('mongoose')
const schema = mongoose.Schema({
    firstName:{
        required:true,
        type:String
    },
    lastName:{
        required:true,
        type:String
    },
    email:{
        required:true,
        unique:true,
        type:String
    },
    address:{
        required:true,
        type:String
    },
    city:{
        required:true,
        type:String
    },
    zipCode:{
        required:true,
        type:Number
    },
    password:String,
    district:{
        required:true,
        type:String
    },
    phoneNumber:{
        required:true,
        type:String
    },
    isLogged:{
        type:Boolean,
        default:true
    },
    isActive:{
        type:Boolean,
        default:true
    },
    isEmailConfirmed:{
        type:Boolean,
        default:false
    },
    quickSignInID:String,
    forgetPasswordCode:String,
    emailConfirmationCode:String
})
module.exports = mongoose.model("User",schema)